////
Dette er en mal for SOSI produktspesifikasjoner som skal være konform med standarden SOSI produktspesifikasjoner - Krav og godkjenning.

Ved bruk av malen, bruk et verktøy som behandler rene tekstfiler (eks notepad, notepad++, emacs, ...) eller et laget for asciidoc (eks ASCIIdocFX)
Vanlig tekst skrives direkte inn i dokumentet.
For generering av html kan f.eks. asciidoctor benyttes.  For generering av pdf kan f.eks. asciidoctor-pdf benyttes.

For forklaring til de enkelte avsnitt, se SOSI produktspesifikasjoner - Krav og godkjenning (PSS) 
https://kartverket.no/globalassets/geodataarbeid/standardisering/standarder/sosi-del-1-generell-del/sosi-produktspesifikasjoner-krav-og-godkjenning-5.0-sosi-generell-del.pdf
og 
Veileder for utarbeidelse av SOSI produktspesifikasjoner (PSV)
https://kartverket.no/globalassets/geodataarbeid/standardisering/veiledere/sosi-produktspesifikasjonerveileder_v2.pdf

Tekst i vinkelparenteser i overskrifter må endres, tekst i hakeparenteser i overskrifter er ikke påkrevd.  Der det er hele seksjoner som kan sløyfes eller gjentas flere ganger (eks. Delomfang), angir kommentarer dette.

Malens endringslogg:
2016 - Nils Egil Søvde - Første versjon (Word-mal)
2021 - Åsmund Tjora - ASCIIdoc-mal
////

//:produktspesifikasjonstype: VANLIG
:produktspesifikasjonstype: STANDARD
// Dersom det er en produktspesifikasjon som skal godkjennes som standard gjennom standardiseringskomiteen for geomatikk, skal produktspesifikasjonstype være satt til "STANDARD". Ellers skal den være "VANLIG".

//Dersom dette er en standardisert produktspesifikasjon, fyll ut denne blokken med riktige verdier:
ifeval::["{produktspesifikasjonstype}" == "STANDARD"]
:standardtype: SOSI-Standardisert Produktspesifikasjon
:standardtittel: Navn på produktspesifikasjon
// Sett inn navnet på standarden
:standardtittelURL: Navn_på_standard
// Sett inn navnet på standarden med "_" i stedet for mellomrom
:standardversjon: 1.0
// Sett inn riktig versjonsnummer
:erstattetversjon: 0
// Sett inn versjonsnummer til forrige versjon av standarden.  La "erstattetversjon" være 0 dersom det ikke er noen tidligere versjoner av standarden.
:standardfulltittel: {standardtittel} {standardversjon}
:fulltittel: {standardtype}: {standardtittel} {standardversjon}
//:forsidebilde: images/forsidebilde_kartverketstandarder.jpg
endif::[]

//Dersom dette ikke er en standardisert produktspesifikasjon, fyll ut denne blokken med riktige verdier:
ifeval::["{produktspesifikasjonstype}" == "VANLIG"]
:fulltittel: Produktspesifikasjon: <Fagområde>[<Leveranse>][<Målgruppe>]-<versjonsnummer>
//:forsidebilde: images/epleblomst.jpg
endif::[]

:publikasjonsdato: 20åå-mm-dd
// sett inn riktig dato over
//:dokumentnivå: UTKAST
:dokumentnivå: HØRING
//:dokumentnivå: TILGODKJENNING
//:dokumentnivå: GODKJENT
//:dokumentnivå: ERSTATTET
//:dokumentnivå: TILBAKETRUKKET
//Sett riktig dokumentnivå.  GODKJENT skal bare benyttes når en standardisert produktspesifikasjon er godkjent i standardiseringskomiteen for geomatikk eller når en ikke-standardisert produktspesifikasjon skal publiseres.


= {fulltittel}
:encoding: utf-8
:lang: nb
// Sett til nn for dokumenter på nynorsk
include::Språk-{lang}.adoc[]
:doctype: book
:pdf-page-size: A4
:toc: left
:toclevels: 4
:sectnums:
:sectnumlevels: 4
:numbered:
:!chapter-signifier: 
:icons: font

//START: URLer til skjema. 
// kode for å velge TEST eller PUB skjemaserver.
ifeval::["{dokumentnivå}" == "UTKAST"]
:skjemaserver: TEST
endif::[]
ifeval::["{dokumentnivå}" == "HØRING"]
:skjemaserver: TEST
endif::[]
ifeval::["{dokumentnivå}" == "TILGODKJENNING"]
:skjemaserver: TEST
endif::[]
ifeval::["{dokumentnivå}" == "GODKJENT"]
:skjemaserver: PUB
endif::[]
ifeval::["{dokumentnivå}" == "ERSTATTET"]
:skjemaserver: PUB
endif::[]
ifeval::["{dokumentnivå}" == "TILBAKETRUKKET"]
:skjemaserver: PUB
endif::[]

ifeval::["{skjemaserver}" == "TEST"]
// url til skjemaserver for ikke-publiserte skjemaer.
:skjemaserverURL: https://skjema.test.geonorge.no/produktspesifikasjon/
endif::[]

ifeval::["{skjemaserver}" == "PUB"]
//url til endelig versjon av skjemaer basert på denne standarden. Sett inn riktig URL
:skjemaserverURL: https://skjema.geonorge.no/produktspesifikasjon/
endif::[]

:gmlskjema: {skjemaserverURL}{standardtittelURL}/{standardversjon}/{standardtittelURL}.xsd
:schematronskjema: {skjemaserverURL}{standardtittelURL}/{standardversjon}/{standardtittelURL}.sch
:rdfskjema: {skjemaserverURL}{standardtittelURL}/{standardversjon}/{standardtittelURL}.rdf

//SLUTT: URLer til skjema

ifeval::["{produktspesifikasjonstype}" == "STANDARD"]
// Merk - alt som står herfra og til kapittelet "Innledning, historikk og endringslogg" vil bare komme med dersom produktspesifikasjonstype er satt til STANDARD øverst i dokumentet.

//URLer og filnavn.  Forandre verdiene til de som gjelder for denne produktspesifikasjonen
:standardurl: https://sosi.geonorge.no/produktspesifikasjoner/{standardtittelURL}
:umlurl: https://sosi.geonorge.no/produktspesifikasjoner/{standardtittelURL}/{standardversjon}/modell.html


ifeval::["{dokumentnivå}" == "UTKAST"]
IMPORTANT: Dette er et utkast til en standard.  Standarden er ikke vedtatt.
endif::[]
ifeval::["{dokumentnivå}" == "HØRING"]
IMPORTANT: Dette er høringsversjonen til {standardtittel} {standardversjon}.  Standarden er ikke vedtatt.
endif::[]
ifeval::["{dokumentnivå}" == "TILGODKJENNING"]
IMPORTANT: Denne standarden venter på godkjenning i Standardiseringskomiteen for Geomatikk. Standarden er ikke vedtatt.
endif::[]
ifeval::["{dokumentnivå}" == "ERSTATTET"]
WARNING: Denne versjonen av standarden er erstattet av en nyere versjon og er ikke lenger anbefalt i bruk.
endif::[]
ifeval::["{dokumentnivå}" == "TILBAKETRUKKET"]
WARNING: Denne standarden er trukket tilbake og er ikke lenger anbefalt i bruk.
endif::[]

****

*Publisert:* {publikasjonsdato} +
*Denne versjonen finnes på:* link:{standardurl}/{standardversjon}[] + 
*Gjeldende versjon finnes på:* link:{standardurl}[] +
ifeval::[{erstattetversjon} != 0]
*Denne versjonen erstatter:* link:{standardurl}/{erstattetversjon}[] +
endif::[]
*Dokumenttype:* {standardtype} +
*link:{umlurl}[HTML-visning av UML-modell]* +

ifeval::["{dokumentnivå}" == "UTKAST"]
Utkast - ikke vedtatt standard
endif::[]
ifeval::["{dokumentnivå}" == "HØRING"]
Høringsversjon - ikke vedtatt standard
endif::[]
ifeval::["{dokumentnivå}" == "TILGODKJENNING"]
Til godkjenning i Standardiseringskomiteen for geomatikk - ikke vedtatt standard
endif::[]
ifeval::["{dokumentnivå}" == "GODKJENT"]
Vedtatt som standard av standardiseringskomiteen for geomatikk
endif::[]
ifeval::["{dokumentnivå}" == "ERSTATTET"]
Denne versjonen av standarden er erstattet av en nyere versjon
endif::[]
ifeval::["{dokumentnivå}" == "TILBAKETRUKKET"]
Denne standarden er trukket tilbake
endif::[]
****

endif::[]

.Lisens
****

//// 
LISENSVILKÅR:  Dersom det er en standardisert produktspesifikasjon gitt ut under SOSI, skal lisensen oppgitt i Lisensvilkår.adoc.  For andre produktspesifikasjoner kan andre lisensvilkår gjelde.
////

include::Lisensvilkår.adoc[]

////
SLUTT Lisensvilkår 
////
****


== Innledning, historikk og endringslogg

=== Innledning

=== Historikk

=== Endringslogg

=== Normative referanser

// Dette delkapittelet er påkrevd i standardiserte produktspesifikasjoner, men er ikke nødvendig i andre produktspesifikasjoner

SOSI Generell del - Regler for UML-modellering - versjon 5.1

SOSI Generell del - SOSI produktspesifikasjoner - Krav og godkjenning - versjon 5.0

Standarder geografisk informasjon - Geodatakvalitet - versjon 1.0

// Listen kan utvides med andre normative referanser

== Definisjoner og forkortelser

// PSV avsnitt 4.Kap 2 viser til standardisert måte å skrive definisjoner (og implisitt forkortelser) på.

=== Definisjoner
// Liste over begreper - termer med definisjoner brukt i standarden. Dersom termene er hentet fra andre standarddokumenter, skal kilde oppgis.  Begrepene bør sorteres alfabetisk etter term.
.term for begrep
[#term_for_begrep]
definisjon på begrepet, skrevet på en slik måte at termen kan byttes ut med definisjonen +
Kilde: Standard eller dokument begrepet er hentet fra +
Merknad: Rundt bruken i dette standarddokumentet
//Det over er eksempel på hvordan en definisjonsblokk kan se ut.  Bytt ut med definisjoner som faktisk er i bruk i standarden.

.term for enda et begrep
[#term_for_enda_et_begrep]
definisjon for enda et begrep, kan referere til <<term_for_begrep>> for å klargjøre hvis man unngår sirkeldefinisjoner

=== Forkortelser
// Forkortelser brukt i standarden
[cols="25,~"]
|===
|SOSI|Samordnet Opplegg for Stedfestet Informasjon 
|===

== Generelt om spesifikasjonen

=== Unik identifisering

==== Kortnavn

////
Identisk med tag 'SOSI_kortnavn' på pakka i EA.

Er case-sensitiv i SOSI-kontroll.

Norske tegn er ok hvis enkoding er riktig innstilt. Kontakt standardiseringssekretariatet hvis du har problemer med norske tegn.
////

==== Fullstendig navn

// Identisk med tag på pakka i EA for SOSI_langnavn.


==== Versjon

// Identisk med tag på pakka i EA for version.


=== Referansedato

// PSS og PSV er litt uklare på hva referansedato er. Det er nevnt gyldighetsdato og utgivelsesdato.


=== Ansvarlig organisasjon

=== Språk

=== Hovedtema

// Fritekst som beskriver hovedtema. Gjerne inspirert av DOK-hovedkategorier eller nasjonal temainndeling: 
// https://register.geonorge.no/subregister/metadata-kodelister/kartverket/nasjonal-temainndeling


=== Temakategori

// Temakategorier er en kodeliste i NS-ISO 19115. Hvis du ikke har tilgang til 19115, finner du en tabell i PSS avsnitt 13.5.2. Det angis én eller flere av kodene i tabellen for temakategorier.


=== Sammendrag

=== Formål

////
PSV har gjemt dette punktet i 4.Kap 3.5/3.6/3.7.

Note: NS-ISO 19131 har som utgangspunkt at en produktspesifikasjon er en bestilling av en (framtidig) geodataleveranse, men det nevnes også at produktspesifikasjoner kan dokumentere eksisterende geodata (noe som er vanlig i Norge).

Brukstilfeller:
Som regel er det behov for dokumentasjon av brukstilfeller som et produkt er tenkt for. En oversiktlig liste med navnene til relevante brukstilfeller kan plasseres under formålskapittelet. Flere detaljer for de nevnte brukstilfellene kan samles i et vedlegg. 
 
I PSS nevnes ikke brukstilfeller, men det er naturlig å plassere de her. En framtidig versjon av ISO 19131 vil ta høyde for det og gi standardiserte føringer for hvor og hvordan brukstilfeller skal dokumenteres.
////

=== Representasjonsform

////
PSV har gjemt dette punktet i 4.Kap 3.5/3.6/3.7.

PSS avsnitt 13.7 har en tabell med mulige verdier.
////

=== Datasettoppløsning

=== Utstrekningsinformasjon

=== Identifikasjonsomfang

// Dette punktet er litt uklart i PSS og PSV. I ISO-standarden for produktspesifikasjoner (NS-EN ISO 19131) er det krav om at identifikasjonen (hele kapittel 3 i denne malen) skal ha en link til den delen av spesifikasjonsomfanget som gjelder hele produktspesifikasjonen (ofte avsnitt 4.1 i denne malen). Forslag til utfylling kan være "hele datasettet" eller "Som angitt i avsnitt 4.<x>.".


=== Supplerende beskrivelse

// Dette punktet er gjemt i PSS 13.6.3 og i PSV 4.Kap 3.12. 
== Spesifikasjonsomfang

(Antall spesifikasjonsomfang: <sett inn antall>)

////
Dette kapittelet beskriver omfang (scopes) i produktspesifikasjonen. Vanligvis vil det være ett omfang, "hele datasettet", som angis i avsnitt 4.1. Merk at 4.1.5 blir gjentagelse fra avsnitt 3.11.

Det kan defineres spesifikasjonsomfang for deler av datasettet, og disse angis i avsnitt 4.2-4.x. Andre spesifikasjonsomfang er nødvendig hvis produktspesifikasjonens (kapittel 5 og utover) har spesifikasjoner som bare gjelder deler av datasettet. I så fall må det refereres til identifikasjonen spesifisert her i kapittel 4.
////

=== Spesifikasjonsomfang for hele spesifikasjonen

////
Se 3.11 og 3.12.
Identiske omfang trenger ikke gjentas.
////

==== Identifikasjon

==== Nivå

==== Navn

==== Beskrivelse

==== Utstrekningsinformasjon

===== Utstrekning beskrivelse

===== Geografisk område

===== Vertikal utbredelse

===== Innhold gyldighetsperiode

// DELOMFANG.  Dersom det er flere delomfang, kopier seksjonen (ned til // SLUTT DELOMFANG)  Dersom det ikke er delomfang, fjern seksjonen

=== Spesifikasjonsomfang for <deler av spesifikasjonen>

==== Identifikasjon

==== Nivå

==== Navn

==== Beskrivelse

==== Utstrekningsinformasjon

===== Utstrekning beskrivelse

===== Geografisk område

===== Vertikal utbredelse

===== Innhold gyldighetsperiode

// SLUTT DELOMFANG

== Innhold og struktur

//MODELL: Repeter denne seksjonen (til // SLUTT MODELL) med underkaptiler dersom flere modeller/omfang er med

=== <Vektor|Raster>baserte data - applikasjonsskjema

==== Omfang

// Skal referere til omfang angitt i kapittel 4

==== UML applikasjonsskjema

//// 
Kjør script for å lage asciidoc-dokumentasjon fra applikasjonskjemamodellen, og lagre resultatet i en tekstfil med navn som slutter på .adoc (f.eks. modell.adoc).

Include-linja under antar at modelldokumentasjonen heter modell.adoc og ligger i samme katalog som fila du jobber med nå - forandre navn og legg på stiinformasjon dersom det er nødvendig.
(eks: 
  include::applikasjonsskjema.adoc[leveloffset=1,lines=2..-1]
  include::skjemadok/modell.adoc[leveloffset=1,lines=2..-1]
  include::/modelldokumentasjon/hagebruk.adoc[leveloffset=1,lines=2..-1] 
  
  Merk at "leveloffset" og "lines" i inkluderingssetningen antar at resultatet av scriptet har en tittel i linje 1 som ikke skal være med, og at overskriftnivået er ett nivå høyere enn det det skal være i produktspesifikasjonsdokumentet.  Dersom skriptet er modifisert slik at disse antakelsene ikke stemmer, kan leveloffset og/eller lines fjernes/modifiseres.
)
////

include::modell.adoc[leveloffset=1,lines=2..-1]

// SLUTT MODELL


== Referansesystem

(Antall lovlige romlige koordinatsystem for dette produktet: <sett inn antall>)

// ROMLIG_REFERANSESYSTEM.  Dersom det er flere lovlige referansesystem, repeter seksjonen (ned til // SLUTT ROMLIG_REFERANSESYSTEM)

=== Romlig referansesystem [<id>]

==== Omfang

==== Navn på kilden til referansesystemet

==== Ansvarlig organisasjon for referansesystemet

==== Link til mer info om referansesystemet

==== Koderom

==== Identifikasjonskode

==== Kodeversjon

// SLUTT ROMLIG_REFERANSESYSTEM

// TEMPORALT_REFERANSESYSTEM.  Dersom det ikke benyttes temporalt referansesystem kan denne seksjonen sløyfes (ned til // SLUTT TEMPORALT_REFERANSESYSTEM

=== Temporalt referansesystem

==== Navn på temporalt referansesystem

==== Omfang

// SLUTT TEMPORALT_REFERANSESYSTEM

== Kvalitet

////
Dette kan være et vanskelig kapittel. Det første du bør gjøre er å sjekke hva du anførte som formål i avsnitt 3.8. Hvis du skal bestille data, er det mest naturlig om du her angir kvalitetskrav. Hvis du dokumenterer eksisterende geodata, derimot, bør kvaliteten her beskrive geodataene.

PSS kapittel 17 gir en innføring i kvalitet. Ofte innebærer kvalitet en statistisk analyse av kontrollmålinger av geodata. Hvis dette er helt ukjent for deg, kan du kanskje anføre at geodataene ikke er kontrollert.

Kvalitet kan også angis kvalitativt (noe NS-ISO 19115 og andre også omfatter). Det kan for eksempel være at geodataene er registrert etter en innmålingsinstruks, eller at de er resultat av beregninger beskrevet i en teknisk rapport eller vitenskapelig artikkel. Merk at dette er nært knyttet til kapittel 8.

Kvalitet skal også referere til omfang (scopes) angitt i kapittel 4. I tillegg kan du innenfor kvalitet også spesifisere enkelte deler (også scope), og angi ulike kvaliteter. Merk at norske geodata (SOSI-standarden) har mulighet for kvalitetsangivelse på objekttypene, men slike hører eventuelt hjemme i kapittel 5.

Hvis du (eller din organisasjon) ikke har peiling på kvaliteten til geodataene, er dette nyttig kvalitetsinformasjon som bør nevnes.

Kvalitetsinformasjon skal oppgis for hver av de fem kvalitetselementene som er oppgitt i PSV:
•	Fullstendighet
•	Stedfestingsnøyaktighet
•	Egenskapsnøyaktighet
•	Tidfestingsnøyaktighet
•	Logisk konsistens
Dersom det for et kvalitetselement ikke er mulig å angi noen fornuftig informasjon skal dette oppgis sammen med en forklaring på årsaken.
////

== Datafangst

////
Datafangst skal også referere til omfang (scopes) angitt i kapittel 4.

Datafangst kan være nært knyttet til kapittel 7.
////

== Datavedlikehold

// Merk at "Omfang" skal referere til omfang (scopes) angitt i kapittel 4.

// VEDLIKEHOLDSINFORMASJON.  Dette delkapittelet kan repeteres om nødvendig (ned til // SLUTT_VEDLIKEHOLDSINFORMASJON

=== Vedlikeholdsinformasjon [<id>]

==== Omfang

==== Vedlikeholdsfrekvens

==== Vedlikeholdsbeskrivelse

// SLUTT_VEDLIKEHOLDSINFORMAJON

== Presentasjon

// Merk at "Omfang" skal referere til omfang (scopes) angitt i kapittel 4.

=== Omfang

=== Referanse til presentasjonskatalog

== Leveranse

// Merk at "Omfang" skal referere til omfang (scopes) angitt i kapittel 4.

// LEVERANSEMETODE.  Dette delkapittelet dersom det er flere leveransemetoder (ned til // SLUTT LEVERANSEMETODE

=== Leveransemetode [<id>]

==== Omfang

==== Leveranseformat

===== Formatnavn

===== Formatversjon

===== Formatspesifikasjon

===== Filstruktur

===== Språk

===== Tegnsett

==== Leveransemedium

===== Leveranseenhet

===== Overføringsstørrelse

===== Navn på medium

===== Annen leveranseinformasjon

// SLUTT LEVERANSEMETODE

== Tilleggsinformasjon

// Merk at tilleggsinformasjon skal referere til omfang (scopes) angitt i kapittel 4.

== Metadata

////
Merk at "Omfang" skal referere til omfang (scopes) angitt i kapittel 4.

Merk også at du her skal angi hvilke metadata som skal følge produktet, men ikke selve metadatene.
////

=== Omfang

=== Metadataspesifikasjon

[appendix]
== SOSI-format realisering

////
---Dersom SOSI-format er angitt under leveranseformat i kapittel 11, klippes inn SOSI-format-realiserings-rapport --

Dersom SOSI-format ikke er et leveranseformat, kan dette vedlegget sløyfes
////

[appendix]
== GML realisering

////
--Dersom GML er angitt som leveranseformat i kapittel 11, skal det her angis hvordan applikasjonsskjemaet skal realiseres i GML i form av URL --- 
////

Realiseringen defineres av følgende filer:

* link:{gmlskjema}[GML-skjema]
* link:{schematronskjema}[Schematron-skjema til validering av modellerte restriksjoner]


[appendix]
== Annen nyttig informasjon til brukere



////
--Informasjon, fortrinnsvis av informativ art, som kan være nyttig for brukere, samles i egne vedlegg--- 
////
